spring:
  h2.console:
    enabled: false
  datasource:
    url: jdbc:h2:file:./roulette
  jpa.hibernate:
    ddl-auto: update

auth:
  jwt:
    expirationDays: 5
    secret: ${ROULETTE-SECRET}
    issuer: casino-roulette
